#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

log_emails=$(git config user.email)

if [[ ${log_emails} == *"@gmail.com" || ${log_emails} == *"@qq.com" ]];then
  echo email $log_emails check pass
else
  echo local email $log_emails check failed, please change email and commit again. Only support @gmail.com or @qq.com email
  exit 2;
fi
